#!/bin/sh

os=$(uname -s)

case "$os" in
  FreeBSD)
    freq=$(sysctl -n dev.cpu.0.freq 2>/dev/null)
    [ -n "$freq" ] && echo "${freq}MHz"
    ;;
  Linux)
    awk -F: '/^cpu MHz/ { if ($2 > max) max = $2 } END { printf("%dMHz\n", max) }' /proc/cpuinfo
    ;;
esac

