#!/bin/sh

if [ "$(uname -s)" == "FreeBSD" ]
then
	# Fetch the cpu frequency information from the sysctl command
	freq=$(sysctl -n dev.cpu.0.freq)
	echo "${freq}MHz"
fi

if [ "$(uname -s)" = "Linux" ]
then
	grep -m 1 MHz /proc/cpuinfo | awk '{ sub(/\..*/, "", $4); print $4 "MHz" }'
fi
