#!/bin/sh

if [ "$(uname -s)" == "FreeBSD" ]
then
	# Fetch the temperature from the sysctl command
	temp=$(sysctl -n dev.amdtemp.0.core0.sensor0)
	temp=${temp%C}
	echo "${temp}°C"
fi

if [ "$(uname -s)" = "Linux" ]
then
	sensors | grep Package | awk '{ print $4 }' | sed 's/+//'
fi
