#!/bin/sh

if [ "$(uname -s)" = "FreeBSD" ]
then
	# Fetch the temperature from the sysctl command
	temp=$(sysctl -n dev.amdtemp.0.core0.sensor0)
	temp=${temp%C}
	echo "${temp}°C"
fi

if [ "$(uname -s)" = "Linux" ]
then
	sensors | grep -m1 -E 'Package|Tctl' | awk -F: '{ split($2, a, " "); print a[1] }' | sed 's/+//'
fi
